"""Category-specific RFQ schemas — guided requirement gathering."""

CATEGORY_SCHEMAS = {
    "Beauty & Cosmetics": {
        "label": "Beauty product brief",
        "fields": [
            {"key": "product_type", "label": "Product type", "type": "select",
             "options": ["Serum", "Cream", "Lotion", "Sheet Mask", "Cleanser", "Toner", "Sunscreen", "Lipstick", "Other"]},
            {"key": "volume", "label": "Volume per unit", "type": "text", "placeholder": "e.g. 30ml"},
            {"key": "skin_concern", "label": "Skin concern", "type": "select",
             "options": ["Acne", "Anti-aging", "Brightening", "Hydration", "Sensitive", "Oily", "Combination"]},
            {"key": "key_ingredients", "label": "Key ingredients", "type": "text",
             "placeholder": "niacinamide, hyaluronic acid, vitamin C"},
            {"key": "formulation", "label": "Formulation requirements", "type": "multi",
             "options": ["Vegan", "Organic", "Paraben-free", "Fragrance-free", "Cruelty-free", "Reef-safe", "Sulfate-free"]},
            {"key": "packaging", "label": "Packaging", "type": "select",
             "options": ["Airless pump", "Dropper", "Jar", "Tube", "Bottle", "Sachet", "Compact"]},
            {"key": "target_markets", "label": "Target markets", "type": "multi",
             "options": ["USA", "EU", "Korea", "Japan", "India", "Middle East", "SE Asia", "LATAM"]},
            {"key": "certifications", "label": "Certifications needed", "type": "multi",
             "options": ["cGMP", "ISO 22716", "Leaping Bunny", "COSMOS", "Halal", "Ecocert"]},
            {"key": "branding_model", "label": "Branding model", "type": "select",
             "options": ["Private label", "White label", "Custom OEM"]},
            {"key": "stability_testing", "label": "Stability testing required?", "type": "select",
             "options": ["Yes", "No"]},
        ],
    },
    "Textile & Apparel": {
        "label": "Textile & apparel brief",
        "fields": [
            {"key": "garment_type", "label": "Garment type", "type": "select",
             "options": ["T-shirt", "Hoodie", "Dress", "Pants", "Jacket", "Knitwear", "Activewear", "Underwear", "Other"]},
            {"key": "fabric", "label": "Fabric", "type": "select",
             "options": ["100% Cotton", "Organic Cotton", "Cotton/Poly Blend", "Linen", "Bamboo", "Hemp", "Recycled Poly", "Wool", "Cashmere", "Tencel"]},
            {"key": "weight_gsm", "label": "Fabric weight (gsm)", "type": "text", "placeholder": "e.g. 180"},
            {"key": "construction", "label": "Construction", "type": "select",
             "options": ["Knit", "Woven", "Jersey", "Fleece", "Pique", "French Terry"]},
            {"key": "size_range", "label": "Size range", "type": "multi",
             "options": ["XS", "S", "M", "L", "XL", "XXL", "Custom"]},
            {"key": "colors", "label": "Colors / pantones", "type": "text",
             "placeholder": "Black, Bone, PMS 7480C"},
            {"key": "print_decoration", "label": "Print / decoration", "type": "multi",
             "options": ["None", "Screen print", "DTG", "Embroidery", "Sublimation", "Patches", "Garment dye"]},
            {"key": "labels", "label": "Labels & tags", "type": "multi",
             "options": ["Woven label", "Care label", "Hangtag", "Custom packaging"]},
            {"key": "certifications", "label": "Certifications needed", "type": "multi",
             "options": ["GOTS", "OEKO-TEX", "BSCI", "Fair Trade", "WRAP"]},
            {"key": "target_markets", "label": "Target markets", "type": "multi",
             "options": ["USA", "EU", "UK", "Canada", "Australia", "Japan"]},
        ],
    },
    "Consumer Electronics": {
        "label": "Consumer electronics brief",
        "fields": [
            {"key": "product_type", "label": "Product type", "type": "select",
             "options": ["Wearable", "Audio (headphones/speaker)", "Smart home", "IoT sensor", "Mobile accessory", "Power bank", "Other"]},
            {"key": "stage", "label": "Project stage", "type": "select",
             "options": ["Concept only", "Have schematics", "Have prototype", "Pre-production"]},
            {"key": "wireless", "label": "Wireless tech", "type": "multi",
             "options": ["BLE", "Wi-Fi", "Zigbee", "LoRa", "NFC", "USB-C only"]},
            {"key": "battery", "label": "Battery", "type": "select",
             "options": ["None", "Coin cell", "Li-ion (rechargeable)", "Li-Po", "AA/AAA"]},
            {"key": "enclosure", "label": "Enclosure material", "type": "select",
             "options": ["ABS plastic", "PC plastic", "Aluminum", "TPU/Silicone", "Glass + metal"]},
            {"key": "compliance", "label": "Compliance needed", "type": "multi",
             "options": ["FCC", "CE", "RoHS", "REACH", "UL", "BIS", "PSE", "MIC"]},
            {"key": "target_markets", "label": "Target markets", "type": "multi",
             "options": ["USA", "EU", "UK", "India", "Japan", "Australia", "LATAM"]},
            {"key": "tooling", "label": "Tooling status", "type": "select",
             "options": ["No tools yet", "Existing 3D files", "Existing tooling at another factory"]},
            {"key": "ip_protection", "label": "IP protection priority?", "type": "select",
             "options": ["Critical (NDA + IP transfer)", "Standard NDA", "Open hardware"]},
        ],
    },
}


def schema_for(category: str) -> dict | None:
    return CATEGORY_SCHEMAS.get(category)
